# This will do the same as Java CI build for develop, but this one is for manual purpose on specific branch.

name: Java CI - manual for branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'     
        required: true
  pull_request:
    branches: [ develop ]
jobs:
  build:
    name: Build manual
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch manual
      if: ${{ github.event.inputs.branch != '' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Checkout branch PR
      if: ${{ github.event.inputs.branch == '' }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Maven tests
      run: |
        export MAVEN_HOME=/usr/bin/mvn
        mvn -B clean install -fn --file Realization/backend/aggregator/pom.xml -Prelease -Dspring.profiles.active=test -Dsurefire.rerunFailingTestsCount=5 | perl -pe 'END { exit $status } $status=1 if /BUILD FAILURE/;'
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: logs-all
        path: |
          /home/runner/work/CzechIdMng/CzechIdMng/Realization/backend/core/core-impl/target/surefire-reports
          /home/runner/work/CzechIdMng/CzechIdMng/Realization/backend/tool/target/surefire-reports
          /home/runner/work/CzechIdMng/CzechIdMng/Realization/backend/acc/target/surefire-reports
          /home/runner/work/CzechIdMng/CzechIdMng/Realization/backend/rpt/rpt-impl/target/surefire-reports
          /home/runner/work/CzechIdMng/CzechIdMng/Realization/backend/vs/target/surefire-reports
        retention-days: 5
    